export const HOME = { emergentLink: "emergent-link" };

export const DASHBOARD = {
  root: "dashboard-root",
  newProjectBtn: "new-project-btn",
  projectCard: (id) => `project-card-${id}`,
  openProjectBtn: (id) => `open-project-${id}`,
  deleteProjectBtn: (id) => `delete-project-${id}`,
  createDialog: "create-project-dialog",
  createDialogName: "create-project-name",
  createDialogDesc: "create-project-description",
  createDialogLocation: "create-project-location",
  createDialogSubmit: "create-project-submit",
};

export const WORKSPACE = {
  root: "workspace-root",
  backToProjects: "workspace-back-btn",
  canvas: "workspace-canvas",
  measurementPanel: "measurement-panel",
  measurementArea: "measurement-area-value",
  measurementPerimeter: "measurement-perimeter-value",
  measurementLength: "measurement-length-value",
  measurementNodes: "measurement-nodes-value",
  finishAreaBtn: "finish-area-btn",
  finishLineBtn: "finish-line-btn",
  cancelDrawBtn: "cancel-area-btn",
  toolSelect: "tool-select",
  toolPan: "tool-pan",
  toolArea: "tool-area",
  toolLine: "tool-line",
  toolEdit: "tool-edit",
  zoomIn: "zoom-in",
  zoomOut: "zoom-out",
  zoomReset: "zoom-reset",
  zoomLevel: "zoom-level",
  gridStepSelect: "grid-step-select",
  snapToggle: "snap-toggle",
  exportBtn: "export-btn",
  exportDialog: "export-dialog",
  exportCsvBtn: "export-csv-btn",
  exportPdfBtn: "export-pdf-btn",
  undoBtn: "undo-btn",
  redoBtn: "redo-btn",
  backgroundBtn: "background-btn",
  backgroundDialog: "background-dialog",
  backgroundFile: "background-file",
  backgroundOpacity: "background-opacity",
  backgroundScale: "background-scale",
  backgroundRotation: "background-rotation",
  backgroundCalibrate: "background-calibrate",
  backgroundRemove: "background-remove",
  backgroundToggleVisible: "background-toggle-visible",
  layerPicker: "layer-picker",
  layerOption: (key) => `layer-option-${key}`,
  statusPicker: "status-picker",
  statusOption: (key) => `status-option-${key}`,
  statusCoords: "status-coords",
  statusZoom: "status-zoom",
  statusGrid: "status-grid",
  statusTool: "status-tool",
  statusSnap: "status-snap",
  sidebarAreaItem: (id) => `area-item-${id}`,
  sidebarDeleteArea: (id) => `area-delete-${id}`,
  sidebarLineItem: (id) => `line-item-${id}`,
  sidebarDeleteLine: (id) => `line-delete-${id}`,
  layerFilter: (key) => `layer-filter-${key}`,
  selectedShapeLayer: "selected-shape-layer",
  selectedShapeStatus: "selected-shape-status",
  selectedShapeThickness: "selected-shape-thickness",
  selectedShapeDensity: "selected-shape-density",
  // Tabs
  tabAreas: "tab-areas",
  tabTonnage: "tab-tonnage",
  tabDeliveries: "tab-deliveries",
  // Deliveries
  deliveryLayerSelect: "delivery-layer-select",
  deliveryTonnageInput: "delivery-tonnage-input",
  deliverySourceInput: "delivery-source-input",
  deliveryAddBtn: "delivery-add-btn",
  deliveryItem: (id) => `delivery-item-${id}`,
  deliveryDelete: (id) => `delivery-delete-${id}`,
  // Tonnage summary
  tonnageRow: (layer) => `tonnage-row-${layer}`,
  tonnageTotalPlanned: "tonnage-total-planned",
  tonnageTotalDone: "tonnage-total-done",
  tonnageTotalDelivered: "tonnage-total-delivered",
};
